### ISSUE TITLE
Ads not getting blocked

### ISSUE THREAD

**Issue by piyushvaddoria** [qnblackcat/uYouPlus#1045]
From today in app it's not blocking any ads.

**Comment by unknown-user-md** [comment]
Same here on iPhone 13 Pro uYou 18.08.1

**Comment by goodcccc** [comment]
Happens to me aswell 12 Pro Max 18.08.1

**Comment by Morku** [comment]
@qnblackcat 
It's sad to see how you handle your tickets, after 3 persons shortly in a row reports the same issue, because in fact, the Ads are real.


https://user-images.githubusercontent.com/6276915/228599405-f660c87b-4c1a-425a-bdde-4fce0c103a70.mp4



iOS 16.4
iPhone Xs Max 64GB
Sideloadly
uYouPlus v18.08.1-2.3.1

**Comment by level3tjg** [comment]
> @qnblackcat It's sad to see how you handle your tickets, after 3 persons shortly in a row reports the same issue, because in fact, the Ads are real.

This issue is a duplicate and doesn't follow an issue template. #996

**Comment by Carrotcruncheruk** [comment]
> @qnblackcat 
> 
> It's sad to see how you handle your tickets, after 3 persons shortly in a row reports the same issue, because in fact, the Ads are real.
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/6276915/228599405-f660c87b-4c1a-425a-bdde-4fce0c103a70.mp4
> 
> 
> 
> 
> 
> 
> 
> iOS 16.4
> 
> iPhone Xs Max 64GB
> 
> Sideloadly
> 
> uYouPlus v18.08.1-2.3.1

It's sad to see that people think this app is a paid subscription! If your not happy with something that free pay for YouTube premium
