### ISSUE TITLE
uYou Download failing Error: The Network Connection was Lost

### ISSUE THREAD

**Issue by idkmanwtt** [qnblackcat/uYouPlus#1140]
The uYou download fails on every setting, at exactly 93%, on both WiFi and data, and persists after reinstall of uYou+

This started sometime in the last 5 hours since I downloaded a video 5 hours and 29 minutes ago with no issue

![30D83219-601E-44AC-9140-DB08DED24089](https://github.com/qnblackcat/uYouPlus/assets/69961402/6ac9cb53-23d1-436e-89d5-d0553828c8cf)

**Comment by Xellerate005** [comment]
I've also had this error with any video, this only happens when you go off the app, like back to the home screen then back to the app, it appears to lose connection and stop downloading, and when pressing the retry button, it just say downloading but never progress, try downloading it again, but don't leave the app or turn off the phone

**Comment by idkmanwtt** [comment]
> 

I tried going off the app and it fails on 47% instead, if I don’t switch out of it at all and just stare at it, not even letting the screen dim, it downloads slowly until 93% when it fails immediately

**Comment by AngeloAndreaIsola** [comment]
+1

**Comment by qnblackcat** [comment]
uYou's issue. Please report the problem to MiRO92: https://github.com/MiRO92/uYou-for-YouTube
