### ISSUE TITLE
Permanent crashing on IOS 15.7.5

### ISSUE THREAD

**Issue by peeboiler** [qnblackcat/uYouPlus#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Device info

- iOS/iPadOS version: 15.7.5
- Device model: Iphone 7 plus
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Altstore
- The specific version of uYouPlus (**latest or newest is NOT a version number!**): I have tried both 18.14.1_3.0 as well as a less recent one(s) like ([v17.43.1-2.1])

### Describe the bug

Ahem so app go crash when booted after loading with the YT logo for like 10-20 sec needing reinstall. 

### Steps to reproduce the issue

1. Close the app
2. Crash on reopen requiring reinstall
3. Happens more frequently when having both a video from yt servers playing as well as a downloaded one running or even open (then closing the app)
4, ^
5, can also be reproduced SOMETIMES by being in the downloads/uyou area and closing the app in the background AND/OR swiping down having ur video play at the bottom of the screen so that u can see ur feed (not PIP) and then closing the app. 

### Crash log (if the app crashes)

```shell
Not sure how to provide the entire log so ill put it at the end as screenshots.
```

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

### Additional context

thanks for the hard work.
I use older/many versions because I am broke and not US based meaning no native PIP and so I need the PIP function that seems to have been removed from newer versions plus I could've sworn the ui was better but now I seem to have the same Ui on every version (??)

**LOGS ATTACHED** (_file( types r tweaking_) 

[YouTube-2023-11-17-201303.ips.txt](https://github.com/qnblackcat/uYouPlus/files/13402673/YouTube-2023-11-17-201303.ips.txt)

**Comment by anoadragon453** [comment]
From reading your logs, the following jumped out at me:

```
"exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL"},
"termination" : {"code":2343432205,"flags":6,"namespace":"FRONTBOARD","reasons":["<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:process-launch watchdog transgression: application<com.google.ios.youtube.AKCH5FK63D>:1029 exhausted real (wall clock) time allowance of 60.00 seconds","ProcessVisibility: Background","ProcessState: Running","WatchdogEvent: process-launch","WatchdogVisibility: Background","WatchdogCPUStatistics: (","\"Elapsed total CPU time (seconds): 51.150 (user 51.150, system 0.000), 42% CPU\",","\"Elapsed application CPU time (seconds): 2.502, 2% CPU\"",") reportType:CrashLog maxTerminationResistance:Interactive>"]}
```

It appears that the YouTube app timed out in responding to the system, so iOS SIGKILL'd it. Since the CPU usage was rather high(?) at 42%, it's possible that the app is tight-looping somewhere, causing it to use a lot of CPU, become unresponsive, and ultimately get killed by the OS (rather than crash).

Looks like it crashed while executing on the main thread (`com.apple.main-thread`), though I'm not able to gleam any further information about what the app was doing when it crashed.

I experience similar crashes on my uYouPlus as well, but only when downloaded videos are present. Thus I would assume the timeout is related to that area of the codebase. I think you would need to build and run the app in XCode with the debugger attached in order to figure out which exact line of the codebase the app was at when it crashed.
