### ISSUE TITLE
[v3.0.3] failed to build exit code 6

### ISSUE THREAD

**Issue by krispyking24** [qnblackcat/uYouPlus#1455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.4
- Device model: iphone 12
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): sideloadly

### Describe the issue

fails to build with an exit code 6, [raw log](https://productionresultssa11.blob.core.windows.net/actions-results/eb9acd10-10d8-40bc-8a2b-7932f9fe994e/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-05-09T09%3A39%3A07Z&sig=sIpwASPeT5nkJJdTngzsnAqRptg%2FvNcaWtHBslpRIz8%3D&sp=r&spr=https&sr=b&st=2024-05-09T09%3A29%3A02Z&sv=2021-12-02)

### Steps to reproduce

1. build the app following the tutorial provided [here](https://github.com/qnblackcat/uYouPlus/wiki/Building#method-1-github-action)
2. building fails on step "Prepare YouTube iPA"
![image](https://github.com/qnblackcat/uYouPlus/assets/77263183/f13dcb62-90f6-46b9-9fef-5d1d5c7a9803)

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by daedadu** [comment]
Is it possible that $YOUTUBE_URL is not accessible w/o credentials? The Link has to be accessible from the Internet without any login.

**Comment by krispyking24** [comment]
how do i check/make the link without credentials required?

**Comment by daedadu** [comment]
When I look at your screenshot you probably don't have defined a url at all, because you get $YOUTUBE_URL instead of a google-drive or whatever link

See here
https://github.com/qnblackcat/uYouPlus/wiki/Building and follow the instructions

**Comment by krispyking24** [comment]
as i said in the steps to reproduce i already followed the tutorial and i did put the drive link

**Comment by krispyking24** [comment]
now it's saying the ipa isn't a zip file ![image](https://github.com/qnblackcat/uYouPlus/assets/77263183/ecd9a927-8ea1-4ef2-99c7-a946e488c710)

**Comment by Dev-Godfrey** [comment]
I am having the same issue,
how do I remove credential from the drive link ?

**Comment by krispyking24** [comment]
u go manage access to the file then make it anyone with link instead of restricted

**Comment by Dev-Godfrey** [comment]
> u go manage access to the file then make it anyone with link instead of restricted

I have done that but I still get the error ,i also tried using one drive and google drive.
dose it matter what version of Ipa is uploaded?

**Comment by daedadu** [comment]
> now it's saying the ipa isn't a zip file ![image](https://private-user-images.githubusercontent.com/77263183/329912976-ecd9a927-8ea1-4ef2-99c7-a946e488c710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzIzNDEsIm5iZiI6MTcxNTYzMjA0MSwicGF0aCI6Ii83NzI2MzE4My8zMjk5MTI5NzYtZWNkOWE5MjctOGVhMS00ZWYyLTk5YzctYTk0NmU0ODhjNzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIwMjcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNmY2NTQyZjVkYzhhNzM0YzFhMjhhMjVkYTY4MzYzMmQ3YmQ5OThjY2Q2ZjljNzYwODYzZTExOWIzNTE5MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7L0013NNeIKbQzDejt2VMbRbVNIzX9a4CSGOG22B24)

You see the command that is actually executed? I have/had the same problem. Execute the exact same wget command on a linux machine and see if the ipa is really downlaoded. When I checked it, it did not download the ipa but the website itself that the link refers to. So probably the link needs to be tweaked, that is different for every cloud storage you use, or wget needs to follow a redirection or something like that. To achieve that you have to change the yaml file that contains the command.

In the end I did not manage to get the url for wget right. Because I did not want to go into the weeds here I used the wayback machine to find the ipa that was here in the releases part of the github repo before the google dmca.

If you read the dmca notice on the maintainers twitter post, you will see the date from which on the ipa was removed. So every backup of github, that is prior that date should suffice.

Please don't ask what the wayback machine is and how to use it. The internet and google should be enough for you to find this out. I know this does not help you to get a version newer than 3.0.3. But that is a problem of a future me and a future you :D

I don't know if @qnblackcat actually tested the download from cloud storage providers or if @qnblackcat just deleted the original way of doing it. A view in the git commits should/could show this (which I have not done).

I see a bootstrapping problem here as well. Where do I actually get the ipa from? I don't have enough experience with ios. Can I get ipas from an unrooted iphone? There are a lot of websites that offer the ipa behind some accounts though.

**Comment by qnblackcat** [comment]
@Dev-Godfrey 

## DropBox:

OK, if you want to generate a direct download link from Dropbox, simply change `&dl=0` to `&dl=1` at the end. Fox example:

```
https://www.dropbox.com/scl/fi/utpp5ejl08glssfoh2p17/TestDownload.txt?rlkey=vffedljofmq4oidxdgbcoglqh&st=vqdr3ajz&dl=0
```

will be changed to:
```
https://www.dropbox.com/scl/fi/utpp5ejl08glssfoh2p17/TestDownload.txt?rlkey=vffedljofmq4oidxdgbcoglqh&st=vqdr3ajz&dl=1
```
----

## Google Drive

- Paste the Shared GG Drive uRL to [this page](https://drive.codevn.net) and you'll get the direct link
----

## OneDrive
- OneDrive Persional is ugly. I haven't found an easy way to generate the direct link yet.
- However, if you use Sharepoint, just change everything after `?e=...` to `?download=1`. Fox example:
```
https://27man-my.sharepoint.com/:t:/g/personal/qn____27man_onmicrosoft_com/EWwXvAsZZSZPvdlJjCow2YUB8SlyJoxk1RsPteSEYTjfIA?e=MFbBED
```
will be changed to:
```
https://27man-my.sharepoint.com/:t:/g/personal/qn____27man_onmicrosoft_com/EWwXvAsZZSZPvdlJjCow2YUB8SlyJoxk1RsPteSEYTjfIA?download=1
```

**Comment by krispyking24** [comment]
fixed all the issues by following qnblackcat's advice but didn't work on google drive but drop box worked

**Comment by zehDonut** [comment]
> ## Google Drive
> 
>     * Paste the Shared GG Drive uRL to [this page](https://drive.codevn.net) and you'll get the direct link
> 

Are you sure this works? I only get a 'dl.php' file from the generated link.
