### ISSUE TITLE
[Questions] i'm so sorry but i don't understand anything on this website please help me

### ISSUE THREAD

**Issue by khalvali** [qnblackcat/uYouPlus#1536]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

❌ No, I don't think this is a bug. I will explain below

### My question

I'm first time on github and i don't know how to do anything here. i don't really understand english actually :(
I just want to download uYou IPA pls help me. I did read wiki about building and i don't know how to fork repository and where can i get decrypted YouTube IPA.

**Comment by tigeryu8900** [comment]
You can fork this repository by going [here](https://github.com/qnblackcat/uYouPlus/fork), which you have already done.

You can get the decrypted YouTube IPA from either of the two links. They require setting up an account, but they are free:
- https://decrypt.day/app/id544007664
- https://armconverter.com/decryptedappstore/us/id544007664

When you download the IPA file, copy the direct link to the download. By direct link, I mean the link associated with the downloaded file, not the link to the page where you got the file. If you open this link on another device, it should automatically download without further action.

For decrypt.day, this link looks different depending on how the IPA file is served at the time. However, for armconverter.com, it should look something like this:

```
https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.29.1?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxMzMzNzgsImlhdCI6MTcyMjE0NDk2NiwiZXhwIjoxNzIyMTU1NzY2LCJhcHBpZCI6NTQ0MDA3NjY0LCJhcHB2ZXIiOiIxOS4yOS4xIn0.vYj_ua2G3p58yhWj4C4KXpRvkAsPb0tDfhKRCmpV-Ok
```

Keep in mind that these links expire after some time since the site expects you to download the file immediately.

Now, when you run the workflow [here](https://github.com/khalvali/uYouPluss/actions/workflows/buildapp.yml), paste that download link in the field where it asks for it.

If you still can't get it to work, you can go [here](https://github.com/qnblackcat/uYouPlus/forks?include=active&page=1&period=1mo&sort_by=last_updated) and find a repository that has a successful run.

**Comment by khalvali** [comment]
> You can fork this repository by going [here](https://github.com/qnblackcat/uYouPlus/fork), which you have already done.
> 
> You can get the decrypted YouTube IPA from either of the two links. They require setting up an account, but they are free:
> 
> * https://decrypt.day/app/id544007664
> * https://armconverter.com/decryptedappstore/us/id544007664
> 
> When you download the IPA file, copy the direct link to the download. By direct link, I mean the link associated with the downloaded file, not the link to the page where you got the file. If you open this link on another device, it should automatically download without further action.
> 
> For decrypt.day, this link looks different depending on how the IPA file is served at the time. However, for armconverter.com, it should look something like this:
> 
> ```
> https://armconverter.com/decryptedappstore/download/544007664/com.google.ios.youtube/19.29.1?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxMzMzNzgsImlhdCI6MTcyMjE0NDk2NiwiZXhwIjoxNzIyMTU1NzY2LCJhcHBpZCI6NTQ0MDA3NjY0LCJhcHB2ZXIiOiIxOS4yOS4xIn0.vYj_ua2G3p58yhWj4C4KXpRvkAsPb0tDfhKRCmpV-Ok
> ```
> 
> Keep in mind that these links expire after some time since the site expects you to download the file immediately.
> 
> Now, when you run the workflow [here](https://github.com/khalvali/uYouPluss/actions/workflows/buildapp.yml), paste that download link in the field where it asks for it.
> 
> If you still can't get it to work, you can go [here](https://github.com/qnblackcat/uYouPlus/forks?include=active&page=1&period=1mo&sort_by=last_updated) and find a repository that has a successful run.

Thank you so much! You helped me with the workflow, but now i can't find IPA in release tab. "That's it! Grab a coffee ☕️ It will take a while. You will see the IPA in the Releases tab of your repository." I guess this tab is located on the main repository screen on the right side, as noted in the picture, right? Should there be a file here?
![image](https://github.com/user-attachments/assets/79409853-9c2b-4018-8e5a-1a02d54af5b9)

**Comment by tigeryu8900** [comment]
It won't appear in the releases tab unless you uncheck `Create a draft release`, which I don't recommend since that could be DMCAed. Instead, there should be an artifact on the page of the run. Download that.

![image](https://github.com/user-attachments/assets/445aa3d9-173d-495e-90c1-46fe6b86bc9b)

**Comment by yodaluca23** [comment]
> It won't appear in the releases tab unless you uncheck `Create a draft release`, which I don't recommend since that could be DMCAed. Instead, there should be an artifact on the page of the run. Download that.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/445aa3d9-173d-495e-90c1-46fe6b86bc9b)

No, you should uncheck the upload artifact, and check Create draft. Then go to the releases page, and it will be there as a draft. (You will have to be signed in with the same account that owns the fork).
