### ISSUE TITLE
CercubePlus Vs uYouPlus? Which is better?

### ISSUE THREAD

**Issue by CycIoneTM** [qnblackcat/uYouPlus#218]

**Comment by qnblackcat** [comment]
Feel free to try both of them

**Comment by arichorn** [comment]
I did have a response for which one is better I tell you the stuff from the one another.

**uYouPlus**
uYouPlus comes with the following stuff including:

uYou
iSponsorBlock
YouPiP
YTUHD
YouTube Dislike Return
YTAutoFullScreen
YTClassicVideoQuality
YTNoHoverCards
YTSystemAppearance
YTNoCheckLocalNetwork
YouRememberCaption
NoYTPremium
YTSpeed
YTMiniplayerEnabler
YTDisableHighContrastIcons - exclusive to my forked ver of uYou+ sadly.

**CercubePlus**
and now heres CercubePlus's Version with the following stuff including:

Cercube
iSponsorBlock
YouPiP
YTUHD
YouTube Dislike Return
YTClassicVideoQuality
YTNoHoverCards
YTABGoodies
YouAreThere
YouRememberCaption
YTNoCheckLocalNetwork
NOYTPremium
and more tweaks..

and now that's out of the way I will tell you the downsides one each of uYou & Cercube

Downsides to uYouPlus 2.1-YT16.42.3/YT17.28.2 - 👌
uYou uses 16.42.3, it hasn't updated in a while but it does still work with newer versions of the YouTube app but expect crashes when using uYouPlus recent version including the notifications/channelcustomization crash.

Downsides to CercubePlus 5.3.10-YT17.25.1/YT17.28.2 - ⚠️
1. Cercube still updates frequently but there is a lot amount features that it's missing from uYou itself like the iPad Layout option.
2. Navigation Bar at the top has a problem with the Cercube tweak and which I meant Cercube or iSponsorBlock broke some of the navigation bar on YouTube and some of the YouTube App Elements like Notifications still shows the icon when you're already on the tab.
3. Cercube really annoys me and wants me to sign in to an account just so I can have the ability download videos/shorts/songs and for me personally I don't recommend anyone to make an account or sign in to an account on the Cercube tab since I don't trust it.

Hopefully you readed this and understand the problems with these but my recommendation is uYouPlus if you wanting to do stuff like Downloading content without signing in or having less features and problems unlike Cercube/CercubePlus. uYouPlus is a pretty good tweak from the dev qnblackcat themselves! ✌️
