### ISSUE TITLE
[Questions] How to donate?

### ISSUE THREAD

**Issue by alexandrius** [qnblackcat/uYouPlus#252]
Hey qnblackcat 👋 !

Been using uYouPlus for me and my friends for months! Absolutely amazing build - Thanks for that.

I'm afraid you'll lose motivation for maintaining uYouPlus. I want to donate some money to you. Pretty sure other people would love to do the same.
I suggest adding https://www.buymeacoffee.com/ or some other service to the README.md

Great job!

**Comment by qnblackcat** [comment]
First of all, I really appreciate your support. It means a lot to me.

Back in the day I released Better Cercube (~2 years ago), I never intended to make anything like this. Sideloading is my hobby and I just want to share my work with people. That's why I’ve never asked for donating, because,... things are less fun when you doing it for money, you know... Furthermore, uYouPlus was built on hard work from many [developers](https://github.com/qnblackcat/uYouPlus#credits) (MiRO92, PoomSmart, Galatic dev, level3tjg, BandarHL...). I think they deserve the support than me, lol. 

Anyway, if you still want to support me, then I do have a Paypal account here: https://paypal.me/qnblackcat. I’ll try to keep uYouPlus up to date as long as I can (for free of course).

**Comment by alexandrius** [comment]
Sorry for late reply. I did donate but I suggest adding that to README.md so that everyone else can find your PayPal easily.

Thanks again

**Comment by qnblackcat** [comment]
@alexandrius Thank you! I really appreciate your support!
