### ISSUE TITLE
[Bug] Hide Previous and Next Button is broken at latest version

### ISSUE THREAD

**Issue by ShadowRoi** [qnblackcat/uYouPlus#308]
### Device info
- iOS/iPadOS version: 15.4
- Device model: IPhone 13 Pro
- Sideload tool: AltStore
- Version of uYouPlus: 17.26.2

### Describe the bug
 There is an option in uYouPlus where you can hide the previous and next button. It was working completely fine but now that I updated on the latest uYouPlus version it’s broken.

**Comment by qnblackcat** [comment]
try [this](https://27man-my.sharepoint.com/:u:/g/personal/qn____27man_onmicrosoft_com/EUrRD0ErzK1NvDgGZ7YqZQUBUcxYlfAGvxeWj7oGYcprRQ?download=1)

**Comment by arichorn** [comment]
@qnblackcat sorry to ping you but check out the normal version of YouTube on the app
![775EC77B-C29A-407C-95A1-A6A2B144A115](https://user-images.githubusercontent.com/78001398/181513399-03370cea-3df3-4ec7-b9cc-dfd1ffc2b26f.jpeg)
The buttons have changed to this and now YouTube removed the Previous and Next buttons on the video player
![FE8F58ED-7E6D-4153-A30F-AD53F95E1A8E](https://user-images.githubusercontent.com/78001398/181513400-576381b1-a9f7-4a9b-b6d3-647d6fc8fa32.jpeg)
But they only show up at the end of the video but this is the info I got and explains why the functions broke with previous and next since YouTube 17.26.2 or newer has this new Video Player UI

**Comment by jeffzyliu** [comment]
I had the same issue. The F1 ipa linked above fixed it for me.

**Comment by qnblackcat** [comment]
@jeffzyliu thanks for letting me know

**Comment by arichorn** [comment]
yep it worked too
