### ISSUE TITLE
[Bug] Error when refreshing or installing

### ISSUE THREAD

**Issue by TheNerdyBlock** [qnblackcat/uYouPlus#360]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: iPadOS 16 beta 5
- Device model: iPad Pro 12.9" 5th Generation
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly and Altstore
- Version of uYouPlus: 17.26.2-2.1

### Describe the bug
Everytime I try to refresh or update my install of uYouPlus I get the following error
![image](https://user-images.githubusercontent.com/48140896/183814725-530715e0-e63e-4f19-a4a1-827034ff70a5.png)
The only way to get the installation to go through is to delete the app and install fresh, causing all settings to be reset. It has been like this for months. If I try using Altstore I get the same error. 

### How to reproduce the bug
Refresh or update uYouPlus using either Sideloadly or Altstore

### Crash log (if possible)
_(The crash log can be found in the  Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)_
There is no crash log since the error happens in the sideloading tool. 

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_
This is an error with the sideloading itself. 

### Additional context: 
I know this is an issue with uYouPlus because BHTwitter (https://github.com/BandarHL/BHTwitter) installs and updates fine. I love the app, I hope this can be sorted out soon.

**Comment by fefifofum** [comment]
I have the same issue sideloading with Signum. I can update other apps without issues, only uYouPlus fails.

**Comment by ildallo** [comment]
I also have the same problem. I tried uninstalling and reinstalling the app by deleting it from the phone, and it worked (like two weeks ago). However, the issue is that now you can't do that because otherwise it won't let you log in anymore. Furthermore, I read online that the error is probably due to the incorrect .ipa file.

**Comment by vcrtech** [comment]
Same issue. AltStore just hangs indefinitely when trying to install the latest version. I was able to refresh the previous version so it did not overwrite that (thankfully). Afraid to try delete and reinstall due to running out of app IDs and losing the sign-in.

**Comment by levochkaa** [comment]
Same issue on all iOS 16 betas (3-5) that I've used. To fix this I delete the app from iPhone and install again.

**Comment by buitim** [comment]
This might be a similar issue, but when I attempt to update via AltStore, the installation just hangs and all of my other signed apps stop working as well. A solution I've found is to delete and reinstall AltStore and uYouPlus. Running iOS 16 dev beta 5

**Comment by qnblackcat** [comment]
#### The situation:
- Since uYouPlus v17.17.4-2.1, [Open in YouTube extension](https://github.com/CokePokes/YoutubeExtensions.git) was added to uYouPlus. 
- We all know that free user only have 10 App IDs per week. Sideloading YouTube literally takes 6 app ids (1 for YouTube, 5 for its Plugins). If **Open in YouTube extension** is present, then we'll need 2 more app ids for it. **8 app ids just for a single app is definitely not OK.** Don't forget we also need 2 app ids for AltStore itself.
- To address this problem, I have to remove all the Plugins (extensions) of YouTube, so uYouPlus only needs 3 app ids in total. Note that those Plugins are not necessary at all, and can be removed safely.

#### So what the fuck is happening? 
- In my theory, if you've ever installed any YouTube app with all of its extensions, AltStore/Sideloadly probably saves a copy of the app somewhere on your device (to shorten the refresh time I guess).
- Now, when you come to uYouPlus, AltStore/Sideloadly will look for those extensions, but they are removed. So they're crying about extensions missing. 

#### What can I do?
- I can do nothing.

#### Is there a workaround?
- Just select "Remove app extensions" when installing the app (both AltStore/Sideloadly). Keep in mind that you won't be able to use Open in YouTube extension anymore. [More info](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-deep-link-aka-open-in-the-youtube-app-doesnt-work).

**Comment by vcrtech** [comment]
Oh nice! I was under the impression that SponsorBlock and friends were extensions and I had to click “keep” for them to work. Now I feel foolish :D I will give it a try with “remove” as soon as my days are up.Thank you!!On Aug 13, 2022, at 13:44, Nguyễn Đạt ***@***.***> wrote:﻿
The situation:

Since uYouPlus v17.17.4-2.1, Open in YouTube extension was added to uYouPlus.
We all know that free user only have 10 App IDs per week. Sideloading YouTube literally takes 6 app ids (1 for YouTube, 5 for its Plugins). If Open in YouTube extension is present, then we'll need 2 more app ids for it. 8 app ids just for a single app is definitely not OK. Don't forget we also need 2 app ids for AltStore itself.
To address this problem, I have to remove all the Plugins (extensions) of YouTube, so uYouPlus only needs 3 app ids in total. Note that those Plugins are not necessary at all, and can be removed safely.

So what the fuck is happening?

In my theory, if you've ever installed any YouTube app with all of its extensions, AltStore/Sideloadly probably saves a copy of the app somewhere on your device (to shorten the refresh time I guess).
Now, when you come to uYouPlus, AltStore/Sideloadly will look for those extensions, but they are removed. So they're crying about extensions missing.

What can I do?

I can do nothing.

Is there a workaround?

Just select "Remove app extensions" when installing the app (both AltStore/Sideloadly). Keep in mind that you won't be able to use Open in YouTube extension anymore. More info.

**Comment by Dragoon853** [comment]
> Is there a workaround?
>   Just select "Remove app extensions" when installing the app (both AltStore/Sideloadly). Keep in mind that you won't be able to > use Open in YouTube extension anymore. [More info](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-deep-link-aka-open-in-the-youtube-app-doesnt-work).

This works. Thanks a ton

**Comment by Morku** [comment]
For me, the issue started from Version 17.26.2-2.1 update to 17.30.3-2.1 and now also from 17.30.3-2.1 to 17.31.4-2.1. Previous updates were fine.

I have to delete uYou, otherwise 'nothing is happening' when try to install. Using Signulous. Is a signing service affected to by "10 App IDs per week"?

After fresh install, I am still Logged In, but have to set settings again.

I had a short contact with Signulous support, because when issue occured, I also switched from AppDB to Signulous, but they don't do anythjing different to other services.

**Comment by TheNerdyBlock** [comment]
Thanks for the help, selecting remove app extensions in Sideloadly seems to have fixed the issue, though I did have to delete the app first then it let me refresh the app.

**Comment by advicepyro** [comment]
I have uYouPlus installed on my two devices and have been running into this problem for a while. Had this installed via AltStore. Tried deleting AltStore and YouTube, reinstalling AltServer, reinstalling the app with an older version while choosing to remove extensions, and installing the newest release. Error kept popping up.

This was resolved by removing both AltStore and YouTube again, restarting the device, and using Sideloadly with the option to remove plugins enabled. Also uninstalled AltStore's Mail plug and used Sideloadly's instead. When uploading an older release of uYouPlus with plugins removed, subsequent updates by uploading a newer uYouPlus release worked.

Upcoming Sideloadly release will support background refreshes, so that takes away a reason to use AltStore.

**Comment by yodaluca23** [comment]
> I have uYouPlus installed on my two devices and have been running into this problem for a while. Had this installed via AltStore. Tried deleting AltStore and YouTube, reinstalling AltServer, reinstalling the app with an older version while choosing to remove extensions, and installing the newest release. Error kept popping up.
> 
> This was resolved by removing both AltStore and YouTube again, restarting the device, and using Sideloadly with the option to remove plugins enabled. Also uninstalled AltStore's Mail plug and used Sideloadly's instead. When uploading an older release of uYouPlus with plugins removed, subsequent updates by uploading a newer uYouPlus release worked.
> 
> Upcoming Sideloadly release will support background refreshes, so that takes away a reason to use AltStore.

Yea, I recently ditched AltStore too I've been using Sidloady sense its a lot less glitchy, I get three apps, and I've heard that rumor to so hopefully that'll come out soon...
Also, there would still be a benefit to AltStore for Updates but it should be easy for sideloady to make it where you can just put in GitHub URL and it fetches the latest release using GitHub Releases API haven't heard anything abt them adding that though....

**Comment by andsoitgoes** [comment]
> 

I just wanted to thank you for this. I never fully understood what was going on with the extensions, until I ended up sandblasting my AltStore install with them.

But I could never, ever get it working on iOS 16.x with Altstore, it would just crap out.

Sideloady kind of worked, but then I had that issue which, thanks to your suggestions, I don't have anymore.

Thank you, so much, for everything!

**Comment by iftekharmurad** [comment]
https://github.com/iftekharmurad/uYouPlus-MyEdit/tree/main/_CodeSignature%20-%20My%20Edit

@qnblackcat can you check this about this issue

**Comment by qnblackcat** [comment]
@iftekharmurad 
What a coincidence. Somehow you and I have the same idea. I‘m planning to silently add this chance in the next release to see if it actually works.

With that being said, I still think this wouldn’t make any difference, because the `CodeSignature` file will be re-generated in the signing process. You can even delete that file without a problem. 

That is my theory so I might be wrong. Still worth a try tho

**Comment by iftekharmurad** [comment]
@qnblackcat
Previous uyou+ app need to delete from device. Then new updated app with changes **CodeResources** file need to install. After that all next uyou+ update versions need to be replace with the CodeResources file which not have MessagesExtension plugins code. It will not work without uninstalling uyou+ app which already have MessagesExtension plugIns codes in CodeResources file.
I think this issue will fix in this way.

**Comment by qnblackcat** [comment]
> Previous uyou+ app need to delete from device. Then new updated app with changes **CodeResources** file need to install. After that all next uyou+ update versions need to be replace with the CodeResources file which not have MessagesExtension plugins code. It will not work without uninstalling uyou+ app which already have MessagesExtension plugIns codes in CodeResources file.
> I think this issue will fix in this way.

The problem are:
1. As I said above, the `CodeResources` file **will be re-generated every time you sign the IPA**. Modifying an unsigned IPA is useless.

_Even if I was wrong, that editing the unsigned IPA will fix the problem:_

2. YouTube comes with 7 extensions in total, the MessagesExtension is just one of them. Perhaps it is uploaded first so it will be reported first. All the remaining extensions can cause the same error. 

3. You still have to manually edit the `CodeResources` every time YouTube release a new version, which is insane...

**Comment by yodaluca23** [comment]
> @iftekharmurad 
> 
> What a coincidence. Somehow you and I have the same idea. I‘m planning to silently add this change in the next release to see if it actually works.
> 
> 
> 
> With that being said, I still think this wouldn’t make any difference, because the `CodeSignature` file will be re-generated in the signing process. You can even delete that file without a problem. 
> 
> 
> 
> That is my theory so I might be wrong. Still worth a try tho

Was it added? In the release that just came out?

**Comment by qnblackcat** [comment]
Yes

**Comment by iftekharmurad** [comment]
@qnblackcat
You was right, it's re-generated the codes again.

**Comment by iftekharmurad** [comment]
@qnblackcat
MessagesExtension.appex file and folders didn't exist in the app then why CodeResources create it again?

**Comment by yodaluca23** [comment]
I successfully updated the app with the latest version using sideloadly without removing the old version!!!! and it saved all my settings!!!!

**Comment by denwi** [comment]
Unfortunately the update 'bricking' still happens for me trying to go from v17.43.1-2.1 to v17.48.2-2.1 (latest at time of writing) with AltStore on iOS 16. I make sure to remove all extensions so it is frustrating to say the least.

Hoping Sideloadly gets wifi refreshing soon, since then I'm sure all of us would ditch AltStore.

**Comment by anonymousaga** [comment]
Even disabling extensions (last time extensions were disabled too), altstore gave issues of the plist.

I tried sideloady to see if altstore would keep the sideloady app updated, but sideloady caused the same issue of plist as well: There was an issue during installation: 0: PackageInspectionFailed (Failed to load Info.plist from bundle at path /private/var/containers/Bundle/Application/2A891978-E8B8-4364-8BD8-D04E3F7850A9/App.app/PlugIns/MessagesExtension.appex; Extra info about "/private/var/containers/Bundle/Application/2A891978-E8B8-4364-8BD8-D04E3F7850A9/App.app/PlugIns/MessagesExtension.appex/Info.plist": Couldn't stat /private/var/containers/Bundle/Application/2A891978-E8B8-4364-8BD8-D04E3F7850A9/App.app/PlugIns/MessagesExtension.appex/Info.plist: No such file or directory) There was an issue during installation: 0: PackageInspectionFailed (Failed to load Info.plist from bundle at path)

**Comment by TheManchineel** [comment]
So basically right now the best thing I can do is stay on the version I have, Google broke authentication and the current procedure to authenticate is somewhat unreliable according to docs, so I'd rather not have to completely uninstall uYouPlus, AltStore et al

**Comment by therealFoxster** [comment]
@qnblackcat Any way around this yet? I can't update uYouPlus without having to delete the app first. I also can't deactivate the app due to the same error. :/

**Comment by qnblackcat** [comment]
> @qnblackcat Any way around this yet? I can't update uYouPlus without having to delete the app first. I also can't deactivate the app due to the same error. :/

That’s unfortunate. But there is still no way around this issue.

**Comment by kassienull** [comment]
It was mentioned earlier in this thread that the fix was removing the extra app extensions - is there a possibility of uploading versions of the IPA with and without the app extensions so people with a paid developer account can still use them?

**Comment by anonymousaga** [comment]
Removing the app extensions only works for sideloady, though, not altstore.

**Comment by kassienull** [comment]
How would I install with AltStore though? I thought the fix was to uninstall/reinstall AltStore on the iOS device then try loading the IPA without loading app extensions?

Either way, I'm getting that error when I try to install the IPA with my developer account.

**Comment by therealFoxster** [comment]
@qnblackcat just out of curiosity, what tool do you use to decrypt IPA files? I've been using bfdecrypt and it doesn't seem to cause this problem

**Comment by qnblackcat** [comment]
@therealFoxster 
On iOS 14, I use frida-ios-dump

On iOS 15, bfdecrypt is the only decrypt tool I know, and it works fine for me

**Comment by therealFoxster** [comment]
That interesting, because I've been using bfdecrypt from level3tjg's repo on an iOS 14 device. When I use those IPA files for the build uYouPlus workflow, the resulting tweaked IPAs deactivate just fine in AltStore without the error
