### ISSUE TITLE
[Bug] DontEatMyContent Not Working (Dynamic Island)

### ISSUE THREAD

**Issue by BatSmacker84** [qnblackcat/uYouPlus#521]
### Device info
- iOS/iPadOS version: iOS 16.1 beta 3
- Device model: iPhone 14 Pro
- Sideload tool: Sideloadly
- The specific version of uYouPlus: 17.39.4-2.1

### Describe the bug

The Dynamic Island is still eating into wide aspect ratio (2:1 or wider) videos.

### How to reproduce the bug

Watch a 2:1 or wider video. The Dynamic Island still eats into it. 

### Crash log (if possible)

No crashing.

### Are you using the newest version of uYouPlus? If not, why?

Newest as of posting the issue.

### Does the issue happen with the official YouTube from AppStore?

No, this is tweak specific. 

### Additional context: 

I brought the issue up with the tweak creator and seemingly fixed it. They released a new version of the tweak (v1.0.1) and it now works when I inject it into uYouPlus when it did not before. Both of us are confused because there should be no difference between the old version and the new one, but it works now. I believe that updating to the newer version of the tweak can fix this issue.

**Comment by qnblackcat** [comment]
> They released a new version of the tweak (v1.0.1) and it now works when I inject it into uYouPlus when it did not before. Both of us are confused because there should be no difference between the old version and the new one, but it works now.

=> This part I don’t understand….

@therealFoxster do you think something conflicts with the tweak?

**Comment by therealFoxster** [comment]
Not that I'm aware of. On my 13 mini, the tweak works fine in the latest version of uYouPlus, which leads me to believe it wasn't caused by a tweak conflict. I might have released the wrong executable binary for v1.0.0, which was why it didn't work (?), so I went and compiled the same code but released it as v1.0.1 (in case v1.0.0 was a dud). 

The code, otherwise, is unchanged, so I don't think there's anything that needs to be done on your end, though it'd be better to have confirmation from users with Dynamic Island, as I personally haven't been able to test the tweak on those devices.

**Comment by therealFoxster** [comment]
@BatSmacker84 you mentioned in your comment [here](https://github.com/therealFoxster/DontEatMyContent/issues/5#issuecomment-1268047866) that you injected the tweak into both the .ipa I provided and uYouPlus (and it works), though I should mention that that wasn't necessary. Both the .ipa I provided and uYouPlus already has the tweak in them so they should work by default. With uYouPlus, you may need to enable the tweak before it can be used (Settings > uYouPlus > Prevent Notch/Island on 2:1 Video Content), but otherwise you shouldn't have to inject the tweak manually.

**Comment by BatSmacker84** [comment]
I injected the new tweak (v1.0.1) into uYouPlus and it worked. When I didn't inject the new tweak and just sideloaded the app the tweak did not work properly. 

uYouPlus has the v1.0.0 tweak that doesn't work for some reason, so in order to make it work I needed to inject the new tweak manually. After doing so it works great.

**Comment by therealFoxster** [comment]
Strange. Did you enable the tweak in uYouPlus settings? Since the code used in uYouPlus and v1.0.1 are largely the same, it's very weird that one works and the other doesn't. 🤔

**Comment by BatSmacker84** [comment]
I restarted the app a few times and reloaded it multiple times as well. The only way I got DEMC to work was injecting v1.0.1 tweak into the IPA while sideloading. After that it works great,

**Comment by therealFoxster** [comment]
> I restarted the app a few times and reloaded it multiple times as well.

Since you didn't mention whether you enabled the tweak in uYouPlus's settings or not, I'm assuming you **did** enable it _(Settings > uYouPlus > Prevent Notch/Island on 2:1 Video Content)_ and it still didn't work. If that's the case, I truly have no clue why it didn't work because like I said, the code used in [uYouPlus](https://github.com/qnblackcat/uYouPlus/blob/main/uYouPlus.xm#L878) and [v1.0.1](https://github.com/therealFoxster/DontEatMyContent/blob/master/Tweak.xm#L8) are identical (aside from a few changes that had to be made to add the tweak to uYouPlus, though those shouldn't have affected its functionality in any way). I'll have to wait to hear from more Dynamic Island users before I can confirm that this is an issue with the tweak and not a one-off.

**Comment by therealFoxster** [comment]
Actually the tweak stopped working for me too just now (v1.0.1). It's been flawless over past 3 weeks but for some odd reason it just went out today. I think I've identified the issue but I'll need to look further into it tomorrow :P

**Comment by therealFoxster** [comment]
Hey @BatSmacker84, can you try the latest version of uYouPlus and let me know if the tweak now works for you? Thanks!

**Comment by BatSmacker84** [comment]
It works now. No manual injection needed.
