### ISSUE TITLE
[Bug] app crash

### ISSUE THREAD

**Issue by Jul9389** [qnblackcat/uYouPlus#715]
## ⚠️ Have you read the [FAQ](https://github.com/qnblackcat/uYouPlus/wiki/FAQ)? Make sure you visit the FAQ page first!!! ⚠️
yes

_Make sure you complete the template. Otherwise, it will be closed without further explanation!_

### Device info
- iOS/iPadOS version: 16.2 (a)
- Device model: iphone 13 pro max
- Sideload tool: Bullfrog assistant
- The specific version of uYouPlus:17.43.1_2.1 
 _**latest** or **newest** is NOT a version number!!_

### Describe the bug
the app crashes automatically when I launch it

### How to reproduce the bug
_(Please attach videos or screenshots if possible)_

### Crash log (if possible)
_(The crash log can be found in the Settings app > Privacy > Analytics & Improvements > Analytics Data > Youtube...)_

### Are you using the newest version of uYouPlus? If not, why? Yes
_(Developers spend time and effort to fix bugs & add improvements with every release. Why don't you update to the latest version before reporting about an issue???)_

### Does the issue happen with the official YouTube from AppStore?
_(Well, YouTube itself is buggy sometimes...)_ No

### Additional context:

**Comment by arichorn** [comment]
https://github.com/arichorn/uYouPlusExtra/releases/tag/v17.46.4-2.1-(404)
here I built this, it’s the uYouPlus Release but I built it. Hopefully this should fix the issues!

**Comment by Jul9389** [comment]
> https://github.com/arichorn/uYouPlusExtra/releases/tag/v17.46.4-2.1-(404)
> 
> here I built this, it’s the qnblackcat/uYouPlus Release except I’m the one who had to built it. Hopefully this should fix the issues!

> thanks man I tell you if it works

**Comment by arichorn** [comment]
Alright 👍

**Comment by Jul9389** [comment]
> Alright 👍

> it's still doesn't work 
https://user-images.githubusercontent.com/117490726/204163160-030ba319-df61-49af-a944-32ab4f928575.MOV

**Comment by qnblackcat** [comment]
Please provide the crash log

**Comment by Jul9389** [comment]
> Please provide the crash log

> there's only one thing i launch and it   directly watch the video so you can understand
 https://user-images.githubusercontent.com/117490726/204202543-f3a99b89-1f3f-4319-b86b-93a87a7d4638.MOV

**Comment by arichorn** [comment]
Provide a crash log, crash logs usually help find and fix the issue of it. 
If you don’t know where it’s at then go to the
Settings App > Privacy & Security > Analytics & Improvements > Analytics Data
and then scroll down and get the YouTube-2022-11-27-{NUMBERS}.ips

**Comment by Jul9389** [comment]
> Provide a crash log, crash logs usually help find and fix the issue of it.
> If you don’t know where it’s at then go to the
> Settings App > Privacy & Security > Analytics & Improvements > Analytics Data
> and then scroll down and get the YouTube-2022-11-27-{NUMBERS}.ips
> i can't open the app because it's crash directly when i open it

**Comment by yodaluca23** [comment]
> > i can't open the app because it's crash directly when i open it

You find the crash log in your iPhones settings app, not the YouTube app.

**Comment by Jul9389** [comment]
>  > i can't open the app because it's crash directly when i open it
> 
> You find the crash log in your iPhones settings app, not the YouTube app.
> 
> 

> ok and then, which file ?![image](https://user-images.githubusercontent.com/117490726/204331111-953cb560-aafd-4f5c-84ac-20c9b9be9187.png)

**Comment by SquiddGame** [comment]
I'm having the same problem on ios 16.1 with Iphone 13 pro since today

**Comment by SquiddGame** [comment]
![5E2C14C3-88E5-4585-A389-D3B7292E8292](https://user-images.githubusercontent.com/106984250/204366114-b2d8957f-8e86-4720-9b7e-f4082eab190b.png)
Hey, Do you need all the crash log or only this ?

**Comment by PoomSmart** [comment]
@SquiddGame just that one is fine

**Comment by Jul9389** [comment]
> @SquiddGame just that one (ips file) is fine

> and what do we do next?

**Comment by PoomSmart** [comment]
Upload the file here..

**Comment by PoomSmart** [comment]
Share button is at the top right.

**Comment by SquiddGame** [comment]
{"app_name":"YouTube","timestamp":"2022-11-28 18:30:23.00 +0100","app_version":"17.43.1","slice_uuid":"5acc00a9-ba9c-3932-a066-3854a9cf7a91","build_version":"17.43.1","platform":2,"bundleID":"MQUZ5HC95W.com.google.ios.youtube","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.1 (20B79)","roots_installed":0,"name":"YouTube","incident_id":"618657E7-43C5-41B2-AE2D-DD732191C2DC"}
{
  "uptime" : 1500000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,2",
  "coalitionID" : 9537,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.1",
    "releaseType" : "User",
    "build" : "20B79"
  },
  "captureTime" : "2022-11-28 18:30:23.0210 +0100",
  "incident" : "618657E7-43C5-41B2-AE2D-DD732191C2DC",
  "pid" : 52755,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-11-28 18:30:21.1916 +0100",
  "procStartAbsTime" : 37006980638248,
  "procExitAbsTime" : 37007024314880,
  "procName" : "YouTube",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/F48943AB-F062-4018-B0C4-AACE22F65073\/YouTube.app\/YouTube",
  "bundleInfo" : {"CFBundleShortVersionString":"17.43.1","CFBundleVersion":"17.43.1","CFBundleIdentifier":"MQUZ5HC95W.com.google.ios.youtube","DTAppStoreToolsBuild":"14B44"},
  "storeInfo" : {"deviceIdentifierForVendor":"11C15E88-AEEE-42DF-AAE2-8145851AAC39","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "MQUZ5HC95W.com.google.ios.youtube",
  "crashReporterKey" : "08d61ce2babcb4a83f9556814bb7f6758f084274",
  "basebandVersion" : "2.12.02",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "ktriageinfo" : "VM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\nVM - pmap_enter retried due to resource shortage\n",
  "asi" : {"libsystem_c.dylib":["abort() called"]},
  "lastExceptionBacktrace" : [{"imageOffset":40584,"symbol":"__exceptionPreprocess","symbolLocation":164,"imageIndex":6},{"imageOffset":96472,"symbol":"objc_exception_throw","symbolLocation":60,"imageIndex":4},{"imageOffset":1566796,"symbol":"+[NSObject(NSObject) _copyDescription]","symbolLocation":0,"imageIndex":6},{"imageOffset":13956588,"symbol":"-[UIResponder doesNotRecognizeSelector:]","symbolLocation":260,"imageIndex":8},{"imageOffset":130976,"symbol":"___forwarding___","symbolLocation":1592,"imageIndex":6},{"imageOffset":557904,"symbol":"_CF_forwarding_prep_0","symbolLocation":96,"imageIndex":6},{"imageOffset":18674144,"imageIndex":13},{"imageOffset":3681732,"symbol":"-[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled]","symbolLocation":84,"imageIndex":8},{"imageOffset":110144,"symbol":"-[UIViewController loadViewIfRequired]","symbolLocation":712,"imageIndex":8},{"imageOffset":109400,"symbol":"-[UIViewController view]","symbolLocation":24,"imageIndex":8},{"imageOffset":3315140,"symbol":"-[UIViewController _setPresentationController:]","symbolLocation":108,"imageIndex":8},{"imageOffset":3308804,"symbol":"-[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:]","symbolLocation":1072,"imageIndex":8},{"imageOffset":3306736,"symbol":"-[UIViewController _presentViewController:withAnimationController:completion:]","symbolLocation":3144,"imageIndex":8},{"imageOffset":3303404,"symbol":"__63-[UIViewController _presentViewController:animated:completion:]_block_invoke","symbolLocation":92,"imageIndex":8},{"imageOffset":3449292,"symbol":"-[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]","symbolLocation":240,"imageIndex":8},{"imageOffset":2850648,"symbol":"-[_UIViewControllerTransitionContext _runAlongsideCompletions]","symbolLocation":140,"imageIndex":8},{"imageOffset":2846696,"symbol":"-[_UIViewControllerTransitionContext completeTransition:]","symbolLocation":128,"imageIndex":8},{"imageOffset":2851144,"symbol":"-[UITransitionView notifyDidCompleteTransition:]","symbolLocation":180,"imageIndex":8},{"imageOffset":2850120,"symbol":"-[UITransitionView _didCompleteTransition:]","symbolLocation":828,"imageIndex":8},{"imageOffset":16991028,"symbol":"__UIVIEW_IS_EXECUTING_ANIMATION_COMPLETION_BLOCK__","symbolLocation":36,"imageIndex":8},{"imageOffset":858120,"symbol":"-[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:]","symbolLocation":636,"imageIndex":8},{"imageOffset":853860,"symbol":"-[UIViewAnimationState sendDelegateAnimationDidStop:finished:]","symbolLocation":436,"imageIndex":8},{"imageOffset":851588,"symbol":"-[UIViewAnimationState animationDidStop:finished:]","symbolLocation":196,"imageIndex":8},{"imageOffset":851864,"symbol":"-[UIViewAnimationState animationDidStop:finished:]","symbolLocation":472,"imageIndex":8},{"imageOffset":77804,"symbol":"CA::Layer::run_animation_callbacks(void*)","symbolLocation":232,"imageIndex":14},{"imageOffset":16348,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":5},{"imageOffset":75764,"symbol":"_dispatch_main_queue_drain","symbolLocation":928,"imageIndex":5},{"imageOffset":74820,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":5},{"imageOffset":632568,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":6},{"imageOffset":507992,"symbol":"__CFRunLoopRun","symbolLocation":2036,"imageIndex":6},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":6},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":7},{"imageOffset":3810256,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":8},{"imageOffset":3809332,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":8},{"imageOffset":551452,"imageIndex":9},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":10}],
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":15690319,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":8787665141},{"value":6089810528},{"value":110},{"value":0},{"value":2361985232948761843},{"value":2361985224039238579},{"value":512},{"value":11},{"value":11},{"value":2095104},{"value":2043},{"value":4120907792},{"value":328},{"value":8945770304,"symbolLocation":0,"symbol":"_main_thread"},{"value":0},{"value":6},{"value":259},{"value":8945770528,"symbolLocation":224,"symbol":"_main_thread"},{"value":0},{"value":260},{"value":0},{"value":8945770528,"symbolLocation":224,"symbol":"_main_thread"},{"value":10769399168},{"value":15},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":8788435372},"cpsr":{"value":1073745920},"fp":{"value":6089810384},"sp":{"value":6089810352},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":8515404288,"matchesCrashFrame":1},"far":{"value":8900050768}},"queue":"com.apple.main-thread","frames":[{"imageOffset":29184,"symbol":"__pthread_kill","symbolLocation":8,"imageIndex":0},{"imageOffset":29100,"symbol":"pthread_kill","symbolLocation":268,"imageIndex":1},{"imageOffset":134284,"symbol":"abort","symbolLocation":180,"imageIndex":2},{"imageOffset":72588,"symbol":"abort_message","symbolLocation":132,"imageIndex":3},{"imageOffset":6784,"symbol":"demangling_terminate_handler()","symbolLocation":336,"imageIndex":3},{"imageOffset":122172,"symbol":"_objc_terminate()","symbolLocation":144,"imageIndex":4},{"imageOffset":69416,"symbol":"std::__terminate(void (*)())","symbolLocation":20,"imageIndex":3},{"imageOffset":69316,"symbol":"std::terminate()","symbolLocation":56,"imageIndex":3},{"imageOffset":16368,"symbol":"_dispatch_client_callout","symbolLocation":40,"imageIndex":5},{"imageOffset":75764,"symbol":"_dispatch_main_queue_drain","symbolLocation":928,"imageIndex":5},{"imageOffset":74820,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":44,"imageIndex":5},{"imageOffset":632568,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":6},{"imageOffset":507992,"symbol":"__CFRunLoopRun","symbolLocation":2036,"imageIndex":6},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":6},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":7},{"imageOffset":3810256,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":8},{"imageOffset":3809332,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":8},{"imageOffset":551452,"imageIndex":9},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":10}]},{"id":15690338,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690339,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690340,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690341,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690342,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690343,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":2888,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77832,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78408,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4236,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502512,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":6},{"imageOffset":507188,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":6},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":6},{"imageOffset":271156,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":11},{"imageOffset":270876,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":11},{"imageOffset":5075772,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":8},{"imageOffset":374792,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":15690344,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690350,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690351,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]},{"id":15690379,"name":"com.apple.NSURLConnectionLoader","frames":[{"imageOffset":2888,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77832,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78408,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4236,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502512,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":6},{"imageOffset":507188,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":6},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":6},{"imageOffset":2450856,"imageIndex":12},{"imageOffset":374792,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":11},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":1},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":1}]},{"id":15690383,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8515375104,
    "size" : 225276,
    "uuid" : "ff27fc8f-90ba-3332-ab7a-c5bc2d9ca7b1",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8788406272,
    "size" : 49152,
    "uuid" : "1aa3a4b6-f9e7-3056-8c8b-4e4dd81312a4",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7620005888,
    "size" : 524280,
    "uuid" : "dad0ce08-8f35-3ff4-899e-43dc44eb65a7",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8787578880,
    "size" : 98300,
    "uuid" : "fa871417-be08-3e90-b33c-a6aa89813f3b",
    "path" : "\/usr\/lib\/libc++abi.dylib",
    "name" : "libc++abi.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7381975040,
    "size" : 278048,
    "uuid" : "ab79707f-af64-3ba5-8899-3b711c6cff5c",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7619715072,
    "size" : 290816,
    "uuid" : "fea36690-a000-3c55-b700-9120b05aa69b",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7496155136,
    "size" : 4087808,
    "uuid" : "5cdc5d9a-e506-3740-b64e-bb30867b4f1b",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8456130560,
    "size" : 36864,
    "uuid" : "a633a095-1226-3942-8f41-3877660185ee",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7531532288,
    "size" : 25026560,
    "uuid" : "179501b6-0fc2-344a-b969-b4e3961ebe10",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4377067520,
    "size" : 13008896,
    "uuid" : "5acc00a9-ba9c-3932-a066-3854a9cf7a91",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/F48943AB-F062-4018-B0C4-AACE22F65073\/YouTube.app\/YouTube",
    "name" : "YouTube"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8006627328,
    "size" : 536592,
    "uuid" : "cb3ff411-4762-34d2-86a4-eca13f9fb6c3",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7399538688,
    "size" : 9740288,
    "uuid" : "c431acb6-fe04-3d28-b677-4de6e1c7d81f",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7514513408,
    "size" : 3964928,
    "uuid" : "edb0559f-c996-327f-9b3a-6616e316f24d",
    "path" : "\/System\/Library\/Frameworks\/CFNetwork.framework\/CFNetwork",
    "name" : "CFNetwork"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4440096768,
    "size" : 27361280,
    "uuid" : "b8d1abdb-f036-348f-a8a6-e6e7b9657d74",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/F48943AB-F062-4018-B0C4-AACE22F65073\/YouTube.app\/Frameworks\/uYou.dylib",
    "name" : "uYou.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7519805440,
    "size" : 3526656,
    "uuid" : "046338bf-09cf-3414-bc93-31296b97eb2d",
    "path" : "\/System\/Library\/Frameworks\/QuartzCore.framework\/QuartzCore",
    "name" : "QuartzCore"
  }
],
  "sharedCache" : {
  "base" : 7381221376,
  "size" : 2907865088,
  "uuid" : "42497769-782f-3bdf-805d-28fa51b4aa3f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.1G resident=0K(0%) swapped_out_or_unallocated=1.1G(100%)\nWritable regions: Total=610.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=610.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG raster data                     768K       22 \nColorSync                           64K        4 \nCoreAnimation                      816K       25 \nCoreData                           160K        4 \nCoreData Object IDs               4112K        2 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           584.2M      106 \nMALLOC guard page                  192K       12 \nMach message                        16K        1 \nSQLite page cache                 2048K       16 \nSTACK GUARD                        192K       12 \nStack                             6992K       12 \nVM_ALLOCATE                        672K       11 \n__AUTH                            3678K      520 \n__AUTH_CONST                      28.3M      715 \n__CTF                               756        1 \n__DATA                            47.3M      714 \n__DATA_CONST                      39.6M      725 \n__DATA_DIRTY                      3533K      606 \n__ETC                              112K        1 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       325.5M       12 \n__OBJC_CONST                      6811K      498 \n__OBJC_RO                         78.5M        1 \n__OBJC_RW                         2429K        1 \n__TEXT                           844.7M      740 \ndyld private memory                640K        3 \nlibnetwork                         640K       16 \nmapped file                      186.8M       48 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.1G     4836 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6081ed9716bb6d61d81d5014",
      "factorPackIds" : {
        "BIFROST_PROD_1" : "63836b5f96e8d228551ec179"
      },
      "deploymentId" : 240002091
    },
    {
      "rolloutId" : "610d52e1fc54bc3389840408",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ATTENTION_ASSETS" : "62ec732bc682040ba94e6a4b",
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6348ac9ca52bb16adc4e4d54",
        "SIRI_UNDERSTANDING_NL" : "62fcee09a9a700130f60d99e",
        "SIRI_EXPERIENCE_CAM" : "62f5c37ae66958407ff7c3ec",
        "SIRI_UNDERSTANDING_MORPHUN" : "62ec7220c682040ba94e6a20"
      },
      "deploymentId" : 240000507
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "91fa35c1-b324-47ed-8479-e40a13957a3e",
      "experimentId" : "6321d5c1172f615946c3e690",
      "deploymentId" : 500000003
    },
    {
      "treatmentId" : "0bbce121-a80b-43a9-a525-8a38fadbaa11",
      "experimentId" : "620ebc346508065773aa3ef8",
      "deploymentId" : 400000033
    }
  ]
}
}

**Comment by SquiddGame** [comment]
Just tried to sideload uyouplus with another app and it does not crash, I guess its due to the sideloading app I use (which is Bullfrog).
This crash is happening since the Bullfrog app was updated (about 3d ago).

**Comment by Jul9389** [comment]
> Just tried to sideload uyouplus with another app and it does not crash, I guess its due to the sideloading app I use (which is Bullfrog).
> 
> This crash is happening since the Bullfrog app was updated (about 3d ago). 
> 
> 

> yeah i think bullfrog app has a problem

**Comment by MrZomka** [comment]
This happens on TrollStore. (A15, 15.2.1)

**Comment by qnblackcat** [comment]
Closed because it is not an issue of uYou+
