### ISSUE TITLE
[Feature Request] Version without extensions stripped.

### ISSUE THREAD

**Issue by yodaluca23** [qnblackcat/uYouPlus#744]
It would be nice if for every version of uYou+ you could also post one that doesn't have all the "unnecessary" extensions, stripped for people who don't have limited app IDs. You could like after the name have something like "With_Extensions". Because I would like to be able to have the YouTube iMessage extension, notification extension, etc.

**Comment by qnblackcat** [comment]
> … I would like to be able to have the YouTube iMessage extension, notification extension, etc.

95% of the time those extensions don’t work because due to sideloading’s limitations. 

Unless you’re using TrollStore, there is no point in keeping those exts. In that case, you could modify [this part](https://github.com/qnblackcat/uYouPlus/blob/76837d0ce7e70046f306e585a69edc63edb20cea/buildapp.sh#L34)in the building process, and then make your own ipa

Furthermore, having 2 ipas in a release is a bad idea cuz it confuses people a lot.
