### ISSUE TITLE
[Bug] Subtitles won’t show in auto playing video in feed. 

### ISSUE THREAD

**Issue by ghost** [qnblackcat/uYouPlus#809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I read the FAQ

### Device info

- iOS/iPadOS version: ios 16.2
- Device model: iPhone xr
- Sideload tool (AltStore, Sideloadly, TrollStore,...): Sidestore
- The specific version of uYouPlus (**latest** or **newest** is NOT a version number!): 17.49.6_2.1

### Describe the bug

In regular youtube this works 100%, i have tried every single setting and different settings it doesn’t change anything. i also can’t toggle to play music in the feed when it’s a song that’s playing. the volume button is missing

also the album artwork for downloaded music is horribly squished. very much an eyesore, taylor swift looks like taylor squished

https://streamable.com/otmkui

### Steps to reproduce the issue

1. Watch a video through the home feed
2. Watch music through the home feed
3. Download music

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, It doesn't

**Comment by justkeepwalking99** [comment]
the captions not appearing in the video feed is a uyou problem. it works on regular youtube

**Comment by justkeepwalking99** [comment]
The newest youtube update fixed the scrolling up in youtuber feed glitch. not showing enough of the top and new bubbles in comments to click. it has me scroll down on the comments when i’m full screen instead of scroll to the side to close them. and it shows the subtitles in youtube videos. But i think you’d have to reapply uyou to the newest version instead of just having it all stay on the december 2022 update. it’s not server side changes it’s on the updated version.

**Comment by qnblackcat** [comment]
Fixed in uYou 3.0

**Comment by qnblackcat** [comment]
Fixed in [v18.15.1-3.0](https://github.com/qnblackcat/uYouPlus/releases/download/v18.15.1-3.0/uYouPlus_18.15.1_3.0.ipa)
