### ISSUE TITLE
[Questions] Replace with your question

### ISSUE THREAD

**Issue by Cryptikdream** [qnblackcat/uYouPlus#913]
### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### Is there an existing issue/question for this?

- [X] I have searched the existing issues

### Do you think this is a bug?

✅ Yes, I believe this is a bug. I will open a new issue with the bug template

### My question

A fix for getting double notifications with it on TrollStore

### Additional context

With it being on TrollStore, there is no way of turning off the notifications from uYou itself, just the original YouTube app. If there is an easy fix for this please let me know. 

I haven’t found anyone else write about this issue.

**Comment by qnblackcat** [comment]
This is not a bug. Nothing to fix

**Comment by Hetyey** [comment]
I’ve also opened an issue about this, but it was closed immediately with the same generic answer because it was “Not related to uYou” (even tho, it is only an issue for this app). I think they don’t care about this because there isn’t a lot of users who are able to use notifications. I found a reddit post (not precisely) about this, and I found another person having the same issue in the comments (no solution): https://www.reddit.com/r/sideloaded/comments/154e00f/double_notifications_uyou/?rdt=49046

**Comment by Kryptikdream** [comment]
I fixed it myself with Signulous!
