### ISSUE TITLE
Feature request: Selectable Video Quality Options

### ISSUE THREAD

**Issue by arichorn** [qnblackcat/uYouPlus#952]
Might be a unique addition to uYouPlus and I know that the section in settings in “Video quality perforeneces” has the options but lets be honest. YouTube did an awful job with that and doesn’t let you pick which quality you really want. Maybe you can add another YouTube viewer controller options. You may be wondering is this a possibility? (Well, Yes)
I think this is a possibility based off of the stuff you’ve done to defaulting the options in the `line 1372` of the `uYouPlus.xm` file. I expect this to be denied since I’m known for suggesting the worst features that no one cares about in uYouPlus.

**Comment by PoomSmart** [comment]
> I expect this to be denied

Because you have never realized you act like an annoying foe in this repo that you often say weird things or suggest odd stuffs - like a kid with non-matured thinking process. We tried to put up with your behavior and warned you few times. Yet you keep doing you.

One of the most ridiculous things you did is to report a bug to this repo but that bug is tested against your own modifications on top of this repo. No average developer will do that. If you expect a bug to be reviewed or checked normally, always and 100% of the time use this repo directly to reproduce the bug.

I even had a couple of DMs pointing... basically that you are still new to contributing to an open-source. You don't realize the DOs and the DONTs. Not everyone is going to tolerate you or cut you some slack because professionalism in an open-source is far-fetched.

This is the final warning. Any further aggression and unfortunately you will be banned from this repo. We had enough.

**Comment by PoomSmart** [comment]
Selectable video quality is a dream feature we wish to implement. If we have time and a will to do, we will work on it. You can leave this issue open.

**Comment by arichorn** [comment]
Apologies I did not mean to close this request. Got scared of the first message. Y’all should’ve told me about that sooner and I’m mature enough to understand stuff like this. You’re a great dev and I hope this warnings will eventually get removed in the future.

**Comment by qnblackcat** [comment]
What’s wrong with the default quality option of uYou?

**Comment by qnblackcat** [comment]
Closed because this is already a feature of uYou
